abuRahmehYanalA1: abuRahmehYanalA1.o abuRahmehYanalA1Main.o
	gcc -Wall -std=c99 abuRahmehYanalA1.o abuRahmehYanalA1Main.o -lm -o abuRahmehYanalA1
abuRahmehYanalA1.o: abuRahmehYanalA1.c givenA1.h
	gcc -Wall -std=c99 -Wall -std=c99 -c abuRahmehYanalA1.c
abuRahmehYanalA1Main.o: abuRahmehYanalA1Main.c givenA1.h
	gcc -Wall -std=c99 -Wall -std=c99 -c abuRahmehYanalA1Main.c 
clean:
	rm *.o abuRahmehYanalA1
